In [3]:
import numpy as np

In [43]:
a = np.matrix([[0, 0, 1, 1, 1, 0, 0, 1],
               [1, 0, 0, 0, 0, 0, 0, 1],
               [1, 1, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 1, 1, 0, 0],
               [1, 1, 0, 0, 0, 0, 0, 0],
               [0, 0, 1, 0, 0, 0, 1, 0],
               [0, 0, 1, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 1, 1, 0],
              ])

In [44]:
a
b = a.transpose()

In [45]:
print(a)

[[0 0 1 1 1 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0]]


In [12]:
print(b)

[[0 1 1 0 1 0 0 0]
 [0 0 1 0 1 0 0 0]
 [1 0 1 0 0 1 1 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 0]
 [0 0 0 1 0 1 0 1]
 [0 0 0 0 0 1 1 1]
 [1 1 0 0 0 0 0 0]]


In [16]:
np.matmul(a, a)

matrix([[2, 2, 1, 0, 2, 2, 1, 0],
        [0, 0, 1, 1, 1, 1, 1, 1],
        [2, 1, 2, 1, 1, 0, 0, 2],
        [1, 1, 1, 0, 1, 1, 1, 0],
        [2, 1, 1, 1, 2, 0, 0, 2],
        [1, 1, 3, 0, 0, 1, 2, 0],
        [1, 1, 2, 0, 0, 0, 1, 0],
        [0, 0, 2, 0, 0, 1, 2, 0]])

In [22]:
c = np.zeros((8,8))

In [46]:
print(a)

[[0 0 1 1 1 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0]]


In [ ]:
"""

[0, 0, 1, 0, 1, 0, 0, 1]
[2, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 1, 2, 1]
[0, 0, 1, 0, 1, 0, 0, 1]
[1, 0, 1, 1, 0, 1, 0, 1]
[0, 0, 1, 0, 1, 0, 2, 0]
[0, 0, 2, 0, 0, 2, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0]

"""

In [28]:
"""
bibliographic adjacency matrix 

[0, 1, 0, 1, 0, 1, 1, 0]
[1, 0, 1, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 2, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 1]
[0, 1, 2, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 1, 1]
[1, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 1, 0, 1, 0, 0]

"""

'\n\n[0, 2, 1, 0, 1, 0, 0, 1]\n[2, 0, 1, 0, 0, 0, 0, 0]\n[1, 1, 0, 1, 1, 1, 2, 1]\n[0, 0, 1, 0, 1, 0, 0, 1]\n[1, 0, 1, 1, 0, 1, 0, 1]\n[0, 0, 1, 0, 1, 0, 2, 0]\n[0, 0, 2, 0, 0, 2, 0, 0]\n[1, 0, 1, 1, 1, 0, 0, 0]\n\n'

In [48]:
d = a * b
np.fill_diagonal(d, 0)
d

matrix([[0, 1, 0, 1, 0, 1, 1, 0],
        [1, 0, 1, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 2, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 2, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 1, 1],
        [1, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 0]])

In [35]:
np.matmul(np.matmul(a,b), a)

matrix([[3, 2, 7, 4, 6, 2, 2, 5],
        [4, 2, 2, 1, 2, 0, 0, 3],
        [6, 5, 6, 1, 3, 1, 2, 2],
        [1, 1, 2, 1, 4, 4, 2, 1],
        [6, 5, 3, 1, 5, 1, 0, 2],
        [1, 1, 7, 1, 2, 6, 7, 1],
        [1, 1, 6, 1, 1, 3, 5, 1],
        [0, 0, 3, 0, 1, 5, 5, 0]])

In [39]:
np.inner(b,a)

matrix([[2, 0, 2, 1, 2, 1, 1, 0],
        [2, 0, 1, 1, 1, 1, 1, 0],
        [1, 1, 2, 1, 1, 3, 2, 2],
        [0, 1, 1, 0, 1, 0, 0, 0],
        [2, 1, 1, 1, 2, 0, 0, 0],
        [2, 1, 0, 1, 0, 1, 0, 1],
        [1, 1, 0, 1, 0, 2, 1, 2],
        [0, 1, 2, 0, 2, 0, 0, 0]])

In [42]:
c = b * a
np.fill_diagonal(c, 0)
c

matrix([[0, 2, 1, 0, 1, 0, 0, 1],
        [2, 0, 1, 0, 1, 0, 0, 0],
        [1, 1, 0, 1, 1, 1, 2, 1],
        [0, 0, 1, 0, 1, 0, 0, 1],
        [1, 1, 1, 1, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 0, 2, 0],
        [0, 0, 2, 0, 0, 2, 0, 0],
        [1, 0, 1, 1, 1, 0, 0, 0]])

In [ ]:
import numpy as np
import matplotlib.pylab as plt
filter_series = data.OffenderIdentifier.isin(offender_list)
new_data = data[filter_series] \
.groupby(['OffenderIdentifier', 'CrimeYear'], as_index=False) \
.agg(AvgAdultOffenders=('NumberAdultOffenders', np.average),
     AvgYouthOffenders=('NumberYouthOffenders', np.average)) \
.sort_values(by=['OffenderIdentifier', 'CrimeYear'], ascending=True)

crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==7540  ]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==7540  ]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==623487]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==623487]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==614546]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==614546]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==189402]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==189402]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==396148]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==396148]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==373749]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==373749]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==120976]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==120976]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==253577]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==253577]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==440431]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==440431]['AvgAdultOffenders'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==300728]['CrimeYear'].tolist()
crimeyear_7540  
avg_adult_7540  
crimeyear_623487
avg_adult_623487
crimeyear_614546
avg_adult_614546
crimeyear_189402
avg_adult_189402
crimeyear_396148
avg_adult_396148
crimeyear_373749
avg_adult_373749
crimeyear_120976
avg_adult_120976
crimeyear_253577
avg_adult_253577
crimeyear_440431
avg_adult_440431
crimeyear_300728
avg_adult_300728 = new_data.loc[new_data['OffenderIdentifier']==300728]['AvgAdultOffenders'].tolist()


list_of_cols = list(zip(
crimeyear_7540  ,
avg_adult_7540  ,
crimeyear_623487,
avg_adult_623487,
crimeyear_614546,
avg_adult_614546,
crimeyear_189402,
avg_adult_189402,
crimeyear_396148,
avg_adult_396148,
crimeyear_373749,
avg_adult_373749,
crimeyear_120976,
avg_adult_120976,
crimeyear_253577,
avg_adult_253577,
crimeyear_440431,
avg_adult_440431,
crimeyear_300728,
avg_adult_300728,
))

df = pd.DataFrame(
    list_of_cols, 
    columns = [
'crimeyear_7540'
,'avg_adult_7540'
,'crimeyear_623487'
,'avg_adult_623487'
,'crimeyear_614546'
,'avg_adult_614546'
,'crimeyear_189402'
,'avg_adult_189402'
,'crimeyear_396148'
,'avg_adult_396148'
,'crimeyear_373749'
,'avg_adult_373749'
,'crimeyear_120976'
,'avg_adult_120976'
,'crimeyear_253577'
,'avg_adult_253577'
,'crimeyear_440431'
,'avg_adult_440431'
,'crimeyear_300728'
,'avg_adult_300728'
    ]
)

plt.plot( 
    'crimeyear_7540', 
    'avg_adult_7540', 
    data=df, 
    marker='o', 
    markerfacecolor='blue', 
    markersize=6, 
    color='skyblue', 
    linewidth=3, 
    label="Offender 7540"
)
plt.plot( 
    'crimeyear_623487', 
    'avg_adult_623487', 
    data=df, 
    marker='o', 
    markerfacecolor='green', 
    markersize=6, 
    color='olive', 
    linewidth=3, 
    label="Offender 623487"
)
plt.plot( 
    'crimeyear_614546', 
    'avg_adult_614546', 
    data=df, 
    marker='o', 
    markerfacecolor='purple', 
    markersize=6, 
    color='plum', 
    linewidth=3, 
    label="Offender 614546"
)
plt.plot(
    'crimeyear_189402', 
    'avg_adult_189402', 
    data=df, 
    marker='o', 
    markerfacecolor='orange', 
    markersize=6, 
    color='yellow', 
    linewidth=3, 
    label="Offender 189402")
plt.plot(
    'crimeyear_396148', 
    'avg_adult_396148', 
    data=df, 
    marker='o', 
    markerfacecolor='red', 
    markersize=6, 
    color='pink', 
    linewidth=3, 
    label="Offender 396148"
)
plt.plot(
    'crimeyear_373749', 
    'avg_adult_373749', 
    data=df, 
    marker='o', 
    markerfacecolor='burlywood', 
    markersize=6, 
    color='peachpuff', 
    linewidth=3, 
    label="Offender 373749"
)

plt.legend()
plt.rcParams["figure.figsize"] = (25,10)
plt.legend(fontsize=12)
plt.xlabel('Year', fontsize=18)
plt.ylabel('Avg Offenders', fontsize=18)
plt.show()